# JStatham
IF (MSVC)
  IF(MSVC_VERSION LESS 1800)
    MESSAGE(FATAL_ERROR "you need Visual Studio 2013 or later")
  ENDIF() 
ELSEIF(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    
ENDIF()

SET(ZBAR_DIR third-party/ZBar)
INCLUDE_DIRECTORIES(${ZBAR_DIR}/include)
INCLUDE_DIRECTORIES(${ZBAR_DIR})

FILE(GLOB ZBAR_SRC
	${ZBAR_DIR}/include/*.[ch]
	${ZBAR_DIR}/*.[ch]
)

LIST(APPEND MMV_SRC ${ZBAR_SRC})

IF (${ARCH_NAME} STREQUAL "x64")
	LIST(APPEND LINK_LIBS ${CMAKE_CURRENT_SOURCE_DIR}/${ZBAR_DIR}/lib/libzbar-x64.lib)
ELSE()
	LIST(APPEND LINK_LIBS ${CMAKE_CURRENT_SOURCE_DIR}/${ZBAR_DIR}/lib/libzbar.lib)
ENDIF()

LIST(APPEND LINK_LIBS ${ZBAR_LIBS})

IF (WIN32)
	LIST(APPEND LINK_LIBS gdi32.lib winmm.lib)
ENDIF()

FILE(GLOB ZBAR_DLLS
	${ZBAR_DIR}/lib/*.dll
)

FOREACH(dll ${ZBAR_DLLS})
	FILE(COPY ${dll} DESTINATION ${PROJECT_BINARY_DIR}/Debug/)
ENDFOREACH()