# JStatham
IF (MSVC)
  IF(MSVC_VERSION LESS 1800)
    MESSAGE(FATAL_ERROR "you need Visual Studio 2013 or later")
  ENDIF() 
ELSEIF(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
    
ENDIF()

SET(ICONV_DIR third-party/ICONV)
INCLUDE_DIRECTORIES(${ICONV_DIR}/include)
INCLUDE_DIRECTORIES(${ICONV_DIR})

FILE(GLOB ICONV_SRC
	${ICONV_DIR}/include/*.[ch]
	${ICONV_DIR}/*.[ch]
)

LIST(APPEND MMV_SRC ${ICONV_SRC})

IF (${ARCH_NAME} STREQUAL "x64")
	LIST(APPEND LINK_LIBS ${CMAKE_CURRENT_SOURCE_DIR}/${ICONV_DIR}/lib/libiconv-static-x64.lib)
ELSE()
	LIST(APPEND LINK_LIBS ${CMAKE_CURRENT_SOURCE_DIR}/${ICONV_DIR}/lib/libICONV.lib)
ENDIF()

LIST(APPEND LINK_LIBS ${ICONV_LIBS})

IF (WIN32)
	LIST(APPEND LINK_LIBS gdi32.lib winmm.lib)
ENDIF()

FILE(GLOB ICONV_DLLS
	${ICONV_DIR}/lib/*.dll
)

FOREACH(dll ${ICONV_DLLS})
	FILE(COPY ${dll} DESTINATION ${PROJECT_BINARY_DIR}/Debug/)
ENDFOREACH()